version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker and Docker Compose"
      - apt-get update && apt-get install -y docker.io
      # Usar una URL estática para descargar Docker Compose y evitar problemas de escape
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - service docker start
  pre_build:
    commands:
      - echo "Decoding the SSH key from Base64"
      - echo "$LIGHTSAIL_SSH_KEY_BASE64" | base64 --decode > /tmp/lightsail-key.pem
      - chmod 400 /tmp/lightsail-key.pem
  build:
    commands:
      - echo "Building Docker images with Docker Compose"
      - docker-compose build
  post_build:
    commands:
      - echo "Deploying to Lightsail using Docker Compose"
      - scp -i /tmp/lightsail-key.pem docker-compose.yml ubuntu@52.20.96.245:/home/ubuntu/
      - ssh -i /tmp/lightsail-key.pem ubuntu@52.20.96.245 "docker-compose down"
      - ssh -i /tmp/lightsail-key.pem ubuntu@52.20.96.245 "docker-compose up -d"
      - echo "Cleaning up SSH key"
      - rm -f /tmp/lightsail-key.pem

artifacts:
  files:
    - '**/*'



# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20.11.0  # Especificar la versión exacta de Node.js
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
#   build:
#     commands:
#       - echo Build started on `date`
#       - grep  -Fq "Congratulations" index.html
#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   baseDirectory: .next
#   files:
#      - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
