version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker and Docker Compose"
      - apt-get update -y
      - apt-get install -y docker.io  # Instalar Docker en Ubuntu
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - nohup dockerd > /var/log/dockerd.log 2>&1 &
      - dockerd-entrypoint.sh &

  pre_build:
    commands:
      - echo "Decoding the SSH key from Base64"
      - echo "$LIGHTSAIL_SSH_KEY_BASE64" | base64 --decode > /tmp/lightsail-key.pem
      - chmod 400 /tmp/lightsail-key.pem

  build:
    commands:
      - echo "Building Docker images with Docker Compose"
      - docker-compose build

  post_build:
    commands:
      - echo "Ensuring Docker is running"
      - scp -o StrictHostKeyChecking=no -i /tmp/lightsail-key.pem -r * ubuntu@52.20.96.245:/home/ubuntu/public_html
      #- ssh -o StrictHostKeyChecking=no -i /tmp/lightsail-key.pem ubuntu@52.20.96.245 "docker-compose down"
      #- ssh -o StrictHostKeyChecking=no -i /tmp/lightsail-key.pem ubuntu@52.20.96.245 "docker-compose up -d"
      - echo "Cleaning up SSH key"
      - rm -f /tmp/lightsail-key.pem

artifacts:
  files:
    - '**/*'






# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20.11.0  # Especificar la versión exacta de Node.js
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
#   build:
#     commands:
#       - echo Build started on `date`
#       - grep  -Fq "Congratulations" index.html
#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   baseDirectory: .next
#   files:
#      - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
