version: 0.2

phases:
  install:
    commands:
      - echo "Decoding the SSH key from Base64"
      - echo "$LIGHTSAIL_SSH_KEY_BASE64" | base64 --decode > /tmp/lightsail-key.pem
      - chmod 400 /tmp/lightsail-key.pem

  pre_build:
    commands:
      - echo "Preparing to copy files to Lightsail"

  build:
    commands:
      - echo "Creating directory in Lightsail if it doesn't exist"
      - ssh -o StrictHostKeyChecking=no -i /tmp/lightsail-key.pem ubuntu@$IP "mkdir -p /home/ubuntu/public_html"

  post_build:
    commands:
      - echo "Copying files to Lightsail instance"
      - scp -o StrictHostKeyChecking=no -i /tmp/lightsail-key.pem -r * ubuntu@$IP:/home/ubuntu/public_html
      - echo "Cleaning up SSH key"
      - rm -f /tmp/lightsail-key.pem

artifacts:
  files:
    - '**/*'







# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 20.11.0  # Especificar la versión exacta de Node.js
#   pre_build:
#     commands:
#       - echo Nothing to do in the pre_build phase...
#   build:
#     commands:
#       - echo Build started on `date`
#       - grep  -Fq "Congratulations" index.html
#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   baseDirectory: .next
#   files:
#      - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
